stages:
  - build
  - test
  - deploy

build:
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose build
  only:
    - frontend_backend
  cache:
    paths:
      - /var/lib/docker/overlay

test-frontend:
  image: node:latest
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test

test-backend:
  image: python:latest
  stage: test
  script:
    - cd backend
    - python -m pip install -r requirements.txt
    - python manage.py test
    
deploy:
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - echo "$DOCKER_PASSWD" | docker login $DOCKER_REPOSITORY --username $DOCKER_USER --password-stdin
  script:
    - docker-compose push
  only:
    - frontend_backend
  environment:
    name: app-service
    url: https://wnetrza.azurewebsites.net
  cache:
    paths:
      - /var/lib/docker/overlay