stages:
  - deploy
    
deploy:
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose build -t wnetrza.azurecr.io/wnetrza:latest
    - echo "$DOCKER_PASSWD" | docker-compose login $DOCKER_REPOSITORY --username $DOCKER_USER --password-stdin
    - docker-compose push wnetrza.azurecr.io/wnetrza:latest
  only:
    - frontend_backend
  environment:
    name: app-service
    url: https://wnetrza.azurewebsites.net
