stages:
  - test
  - deploy

test-backend:
  image: python:3.10
  stage: test
  script:
    - cd backend
    - python -m pip install -r requirements.txt
    - python manage.py test
    
deploy:
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - echo "$DOCKER_PASSWD" | docker login $DOCKER_REPOSITORY --username $DOCKER_USER --password-stdin
    - docker-compose push
  only:
    - frontend_backend
  environment:
    name: app-service
    url: https://wnetrza.azurewebsites.net
