version: "3.2"

services:
  backend:
    restart: always
    container_name: backend
    command : python manage.py runserver 0.0.0.0:8000
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - db-net
    
    image: wnetrza.azurecr.io/backend:latest

  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:3000
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net
    
    image: wnetrza.azurecr.io/frontend:latest

networks:
  db-net:
    driver: bridge
